// libs/react/src/lib/Button/index.tsx
// libs/react/src/lib/Button/Button.tsx
import React from 'react';
import { button } from '@ridge/styles';

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary';
  size?: 'small' | 'large';
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'small',
  className,
  ...props
}) => {
  return <button className={button({ variant, size })} {...props} />;
};

// libs/angular/src/lib/button/button.component.ts
import { Component, Input } from '@angular/core';
import { button } from '@ridge/styles';

@Component({
  selector: 'lib-ridge-button',
  template: `
    <button [class]="buttonClass">
      <ng-content></ng-content>
    </button>
  `,
  standalone: true,
})
export class ButtonComponent {
  @Input() variant: 'primary' | 'secondary' = 'primary';
  @Input() size: 'small' | 'large' = 'small';

  get buttonClass(): string {
    return button({ variant: this.variant, size: this.size });
  }
}
